version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge
